using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using VehicleService.Models;
namespace VehicleService.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
   
    public class VehicleController : ControllerBase
    {
        private readonly VehicleContext _context;
        HttpClient _httpClient;
        

        public VehicleController(VehicleContext context)
        {
            _context = context;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("http://localhost:5176/"); // Base address of the MaintenanceService
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult<IEnumerable<Vehicle>>> GetVehicles()
        {
            // return Ok(_context.Vehicles.FromSqlRaw("exec getallvehicles").ToList());//calling stored procedure using EF Core
            IDbConnection dapper = _context.Database.GetDbConnection();
            IEnumerable<Vehicle> vehicles = dapper.Query<Vehicle>(
                   "getallvehicles",          
                   commandType: CommandType.StoredProcedure
               );
            return Ok(vehicles);
        }
        [HttpGet()]
        [Route("regno/{regno}")]
        public async Task<ActionResult<IEnumerable<Vehicle>>> GetVehiclesByRegno(string regno)
        {
            IDbConnection dapper = _context.Database.GetDbConnection();
            var parameters = new DynamicParameters();
            parameters.Add("@regno", regno, DbType.String, ParameterDirection.Input);
            IEnumerable<Vehicle> vehicles = dapper.Query<Vehicle>(
                   "getvehiclebyregno",
                   parameters,
                   commandType: CommandType.StoredProcedure
               );
            return Ok(vehicles);
        }
        [HttpGet("{id}")]
        public async Task<ActionResult<List<VehicleDTO>>> GetVehicle(int id)
        {
            var vehicle = await _context.Vehicles.FindAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }
            var email = User.Claims.FirstOrDefault(c => c.Type == "email" || c.Type == ClaimTypes.Email || c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.Sub)?.Value ?? "anil@gmail.com";
           //using ef core 
            // return  Ok(_context.Set<VehicleDTO>().FromSqlRaw("SELECT [Type],[Model],[RegnNo],[EngnieCapacity],[Year] FROM [dbo].[Vehicles]").ToListAsync());
            // using dapper
            var connection = _context.Database.GetDbConnection();
            var result = await connection.QueryAsync<VehicleDTO>("SELECT [Type],[Model],[RegnNo],[EngnieCapacity],[Year] FROM [dbo].[Vehicles] WHERE CreatedBy = @Email", new { Email = email });
            return Ok(result);
        }
        [HttpPut("{id}")]
        public async Task<IActionResult> PutVehicle(int id, Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return BadRequest();
            }

            _context.Entry(vehicle).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VehicleExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Vehicle
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        [Authorize]
        public async Task<ActionResult<Vehicle>> PostVehicle(VehicleDTO vehicle)
        {
            

            // Map DTO to Entity
            var vehicleEntity = new Vehicle
            {
                Id = 0, // Id will be generated by the database
                Type = vehicle.Type,
                Model = vehicle.Model,
                RegnNo = vehicle.RegnNo,
                EngnieCapacity = vehicle.EngnieCapacity,
                Year = vehicle.Year,
                CreatedBy = User.Claims.FirstOrDefault(c => c.Type == "email" || c.Type == ClaimTypes.Email || c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.Sub)?.Value
            };
            _context.Database.ExecuteSqlInterpolated($"exec proc_ins_vehicle {vehicleEntity.Type}, {vehicleEntity.Model}, {vehicleEntity.RegnNo}, {vehicleEntity.EngnieCapacity}, {vehicleEntity.Year}, {vehicleEntity.CreatedBy}");
           await _httpClient.PostAsJsonAsync("api/Maintenance/generateSchedule", vehicle); //inter process communication to MaintenanceService to generate maintenance schedule for the newly added vehicle

            return Ok("success");
        }

        // DELETE: api/Vehicle/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteVehicle(int id)
        {
            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            _context.Vehicles.Remove(vehicle);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicles.Any(e => e.Id == id);
        }
    }
}

//create procedure[dbo].[proc_ins_vehicle] (@type varchar(40),
//@model varchar(40),@regnno varchar(15),
//@enginecapacity int,
//@year int,
//@createdby varchar(100))
//as
//insert into vehicles values(@type, @model, @regnno, @enginecapacity,
//@year, @createdby)